//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebinarRegistration.Repo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebinarRegistrationEntities : DbContext
    {
        public WebinarRegistrationEntities()
            : base("name=WebinarRegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Registrant> Registrants { get; set; }
        public virtual DbSet<Webinar> Webinars { get; set; }
        public virtual DbSet<WebinarRegistrant> WebinarRegistrants { get; set; }
    }
}
